first_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from first_app import views

app_name='first_app'

urlpatterns = [
url(r'^user_login/$',views.user_login,name='user_login'),
    # url(r'^second/',views.help,name='second'),
    # url(r'^other/',views.other,name='other'),
    # url(r'^hyper/',views.hyper,name='hyper'),
    # url(r'^folium/',views.folium,name='folium'),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from first_app import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
url(r'^$',views.Undex,name='index'),
url(r'^KNNCosineRecommender',views.other,name='other'),
url(r'^formpage/',views.form_name_view,name='form_view'),
url(r'^admin/',admin.site.urls),
url(r'^folium/',views.folium,name='folium'),
url(r'^supplychainanalysis/',views.hyper,name='hyper'),
url(r'^register/',views.register,name='register'),
url(r'^login/',views.user_login,name='login'),
url(r'^first_app/',include('first_app.urls')),
url(r'^logout/',views.user_logout,name='logout'),
url(r'^special/',views.register,name='special'),
url(r'^foliumv2/',views.folium_Market_Select,name='MS'),
url(r'^profile/',views.profile,name='PF'),
url(r'^matplotlib/',views.mat,name='MAT'),
url(r'^movie_recommender/',views.recommender,name='RS'),
url(r'^movie_recommender_list/*',views.recommender_list,name='RL'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

first_app/models.py
from django.db import models
from django.contrib.auth.models import User
class SAVE(models.Model):
    name=models.CharField(max_length=264)
    email=models.EmailField(max_length=254,unique=True)
    vemail=models.EmailField(max_length=254,unique=True)
    text=models.CharField(max_length=10000)
    # def __str__(self):
    #     return "%s %s %s %s" % (self.name, self.email, self.vemail,
    #     self.text)
# Create your models here.
class Topic(models.Model):
    top_name=models.CharField(max_length=264,unique=True)
    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.DO_NOTHING)
    name=models.CharField(max_length=264,unique=True)
    url=models.URLField(unique=True)
    def __str__(self):
        return self.name
class AccessRecord(models.Model):
    name=models.ForeignKey(Webpage,on_delete=models.DO_NOTHING)
    date=models.DateField()
    def __str__(self):
        return str(self.date)
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username
# class Movie_list(models.Model):
#     movieid = models.CharField(max_length=6)
#     name = models.CharField(max_length=100)
#     date=  models.CharField(max_length=50)
#     address = models.CharField(max_length=100, blank=True)

first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from first_app.models import SAVE
from first_app.models import UserProfileInfo
# def check_for_s(value):
#     if value[0].lower()!='s':
#         raise forms.ValidationError('Need A Start of s/S')
class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs) # Call to ModelForm constructor
        self.fields['username'].widget.attrs['style'] = 'width:200px; height:35px;margin:10px;margin-left:97px;'
        self.fields['email'].widget.attrs['style'] = 'width:200px; height:35px;margin:10px;margin-left:45px;'
        self.fields['password'].widget.attrs['style'] = 'width:200px; height:35px;margin:10px;;margin-left:103px;'
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')
        profile_pic=forms.CharField(widget=forms.TextInput(attrs={'class' : 'myfieldclass'}))
    def __init__(self, *args, **kwargs):
        super(UserProfileInfoForm, self).__init__(*args, **kwargs) # Call to ModelForm constructor
        self.fields['portfolio_site'].widget.attrs['style'] = 'width:400px; height:35px;margin:10px;margin-left:66px;'
        # self.fields['profile_pic'].widget.attrs['style'] = 'margin-left:7.4%;width:205px;height:35px;display: inline-block;padding: 6px 5px 3px 5px;font-size: 15px;cursor: pointer;text-align: center;text-decoration: none;outline: none;color: #fff;background-color: #298089;border: none;border-radius: 5px;box-shadow: 0 4px #999;'
        self.fields['profile_pic'].widget.attrs.update({'class':"custom-file-input",'id':"customFile",'style':'margin-left:97px;width:205px;height:35px;display: inline-block;padding: 6px 5px 3px 5px;font-size: 15px;cursor: pointer;text-align: center;text-decoration: none;outline: none;color: #fff;background-color: #298089;border: none;border-radius: 5px;box-shadow: 2px 3px 5px #999;'})
class FormName(forms.ModelForm):
    name=forms.CharField()
    email=forms.EmailField()
    vemail=forms.EmailField(label='Enter Your Email Again!!')
    text=forms.CharField(widget=forms.Textarea)
    class Meta:
        model=SAVE
        fields='__all__'
    # def clean(self):
    #     all_clean_data=super().clean()
    #     email=all_clean_data['email']
    #     vmail=all_clean_data['vemail']
    #     if email != vmail:
    #         raise forms.ValidationError('Email not Match!!!')
    # # botcatcher=forms.CharField(required=False,widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(6)])
    # # def clean(self):
    #     botcatcher=self.cleaned_data['botcatcher']
    #     if len(botcatcher)==0:
    #         raise forms.ValidationError('Final Countdown')
    #     return botcatcher

first_app/views.py
from django.shortcuts import render
from first_app.models import Topic,Webpage,AccessRecord,SAVE
from first_app.forms import UserForm,UserProfileInfoForm,FormName
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import pandas as pd
import numpy as np
import random
import urllib
from sklearn.neighbors import NearestNeighbors
def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'first_app\_register.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})
def index(request):
    my_dict={'insert_me':'Hello from the other side!!!','check':str(3+5)}
    wblist=AccessRecord.objects.order_by('date')
    date_dict={'access_records':wblist}
    return render(request,'first_app\index.html')
def other(request):
    return render(request,'first_app\other.html')
def mat(request):
    return render(request,'first_app\matplotlib.html')
def hyper(request):
    return render(request,'first_app\hyper.html')
def Undex(request):
    my_dict={'insert_me':'Hello from the other side!!!','check':str(3+5)}
    wblist=AccessRecord.objects.order_by('date')
    date_dict={'access_records':wblist}
    return render(request,'first_app\index.html',date_dict)
def help(request):
    my_dictT={'insert_me':'you do not know me!','help_me':'It is Final Countdown'}
    return render(request,'first_app\second.html',context=my_dictT)
def form_name_view(request):
    form=FormName()
    if request.method=='POST':
        form=FormName(request.POST)

        if form.is_valid():
                form.save(commit=True)
                print('VALIDATION SUCCESS!')
                print('NAME: '+form.cleaned_data['name'])
                print('EMAIL: '+form.cleaned_data['email'])
                print('TEXT: '+form.cleaned_data['text'])
                return Undex(request)
        else:
            print('Validation Not Pass')

    return render(request,'first_app\_formpage.html',{'form':form})
def folium (request):
    return render_to_response('first_app\_2017_m1ymap.html')
def folium_Market_Select (request):
    return render_to_response('first_app\Market_Select.html')

def profile(request):
    return render(request,'first_app\profile.html')
import os
from django.conf import settings
from django.http import HttpResponse

import os
from django.conf import settings
from django.http import HttpResponse

def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'attachment; filename=CV.pdf' + os.path.basename(file_path)
            return response
    raise Http404




@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'first_app\login.html', {})
###############################################################
def recommender(request):
    dft=pd.read_csv('first_app\MCL_R.csv',engine='python')
    lt=['Action', 'Adventure',
       'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western']
    dist1=[]
    dist2=[]
    for i in lt:
        lus=list(dft[dft[i]==1]['name'])
        dist1.append(i)
        dist2.append(lus)
    return render(request,'first_app\movierecommender.html',context={'Dist1':dist1,'Dist2':dist2})
def recommender_list(request):
    dfu=pd.read_csv('first_app\MCL_R.csv',engine='python')
    def movies_concector(MR,Name,n=16,k=5):
        neigh = NearestNeighbors(16,'cosine')
        neigh.fit(MR.iloc[:,23:].values)
        top_k_distances,top_k_movies = neigh.kneighbors(MR.iloc[:,23:].values, return_distance=True)
        Id=int(list(MR.movieid)[list(MR.name).index(Name)])
        listid=[i for i in top_k_movies[Id-1][1:n]]
        distance=[j for j in top_k_distances[Id-1][1:n]]
        lst=[MR.name[r] for r in listid]
        pb=[1/i if i!=0 else 1000 for i in distance]
        ps=[u/sum(pb) for u in pb]
        lstr=list(np.random.choice(lst,k,p=ps,replace=False))
        return lstr
    if 'id' in request.GET:
        print(type(request.GET['id']))
        val=request.GET['id']
        result=movies_concector(dfu,val,n=16,k=11)
        def genre_l(u):
            return [dfu.columns[5:23][ix] for ix,i in enumerate(dfu[dfu.name==u].iloc[:,5:23].values.tolist()[0]) if i==1]
        M_Dict={}
        M_Dict.update({'Name':val,'MovieId':list(dfu[dfu.name==val]['movieid'])[0],'URL_Result':urllib.parse.quote_plus(val),'ADDRESS':list(dfu[dfu.name==val]['address'])[0],'DATE':list(dfu[dfu.name==val]['date'])[0],'Genre':genre_l(val)})
        S_Dict={}
        url_result=[urllib.parse.quote_plus(i) for i in result]
        perid=[list(dfu.name).index(i) for i  in result]
        lislength=list(range(len(result)))
        print(perid)
        S_Dict.update({'Result':result,'Movieid':list(dfu.loc[perid,'movieid']),'URL_Result':url_result,'ADDRESS':list(dfu.loc[perid,'address']),'DATE':list(dfu.loc[perid,'date']),'Genre':[genre_l(g) for g in result]})
        return render_to_response('first_app\movielist.html',locals())
    else:
        return HttpResponseRedirect(request,"first_app\movierecommender.html")

templates/first_app/_formpage.html
<!DOCTYPE html>
{% extends 'first_app/profile.html' %}
{% block body_block %}
{% load staticfiles %}
  <html lang="en" dir="ltr">
    <head>
      <meta charset="utf-8">
      <title>HELLO FUTI</title>
    </head>
    <body>
      <div class="container">
        <form method="post">
         {{form.as_p}}
         {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submitting!">
      </div>
    </body>
  </html>
{% endblock %}

templates/first_app/_register.html
<!DOCTYPE html>
<link href="https://fonts.googleapis.com/css?family=Bitter|Roboto+Slab" rel="stylesheet">
{% extends 'first_app/profile.html' %}
{% load staticfiles %}
{% block body_block %}
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <div class="container">
    <div class="jumbotron" style="background-color:white !important;border-style: solid;border-width: 0.5px 0.5px 0.5px 5px;border-color: #298089;padding-left:8%;margin-left:8%;margin-right:8%;margin-bottom:5%;">
      {% if registered %}
        <h1 style="font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.5px 0.5px #999;">Thank you for registering!</h1>
      {% else %}
        <h1 style="margin-bottom: 35px;font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.5px 0.5px #999;">Register Here!</h1>
        <h2 style="margin-bottom: 20px;font-family:'Roboto Slab',serif;color:#F5B041;;text-shadow: 0.5px 0.5px #999;">Just fill out the form</h2>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="fieldWrapper" >
            {{ user_form.username.errors }}
            <label style="font-family:'Roboto Slab', serif;color:#1F618D;font-size:25px;" for="{{user_form.username.id_for_label}}">Username:</label>
            {{ user_form.username }}
          </div>
          <div class="fieldWrapper">
            {{ user_form.email.errors }}
            <label style="font-family:'Roboto Slab', serif;color:#1F618D;font-size:25px;"for="{{ user_form.email.id_for_label}}">Email Address:</label>
            {{ user_form.email }}
          </div>
          <div class="fieldWrapper">
            {{ user_form.password.errors }}
            <span style="font-family:'Roboto Slab', serif;color:#1F618D;font-size:25px;">{{ user_form.password.label_tag }}</span>
            {{ user_form.password }}
          </div>
          <div class="fieldWrapper">
            {{ profile_form.portfolio_site.errors }}
            <span style="font-family:'Roboto Slab', serif;color:#1F618D;font-size:25px;">{{ profile_form.portfolio_site.label_tag }}</span>
            {{ profile_form.portfolio_site }}
          </div>
          <div class="fieldWrapper">
            {{ profile_form.profile_pic.errors }}
            <span style="font-family:'Roboto Slab', serif;color:#1F618D;font-size:25px;">{{ profile_form.profile_pic.label_tag }}</span>
            {{ profile_form.profile_pic }}
          </div>
          <input type="submit" style='margin-top:15px;border-color:#F1C40F; background-color: #F1C40F;font-size:20px;box-shadow: 2px 2px 5px 0 #999;'class="btn btn-primary" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>
{% endblock %}

templates/first_app/hyper.html
<!DOCTYPE html>
{% extends 'first_app/profile.html' %}
{% load staticfiles %}
{% block body_block %}
<link href="https://fonts.googleapis.com/css?family=Bitter|Roboto+Slab" rel="stylesheet">
    <h2 style="font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.3px 0.3px #999;">Overseas Buyer Recommender Analysis: Suppliers' Relation Network</h2>
    <img src='{% static 'images/圖片1.png' %}' alt='supplier_relation' width="691.5" height="366.5"><br>
    <h2 style="font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.3px 0.3px #999;">Overseas Buyer Recommender Analysis: Buyers' Relation Network 1</h2>
    <img src='{% static 'images/圖片2.png' %}' alt='buyer_relation' width="379" height="410"><br>
    <h2 style="font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.3px 0.3px #999;">Overseas Buyer Recommender Analysis: Buyers' Relation Network 2</h2>
    <img src='{% static 'images/圖片5.png' %}' alt='buyer_relation' width="608.5" height="375" style="PADDING-BOTTOM:15px"><br>
{% endblock %}

templates/first_app/index.html
<!DOCTYPE html>
<link href="https://fonts.googleapis.com/css?family=Bitter|Libre+Baskerville" rel="stylesheet">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
{% extends 'first_app/profile.html' %}
{% load staticfiles %}
{% block body_block %}
<link rel="stylesheet" href="{% static "css/index.css" %}"/>
<div class='container'>
  <div id="divLoading" style='display:block;'>
    <img  rc="{% static 'images/F0949.jpg' %}" style="display:block;position:absolute;margin:0px;padding:0px;max-width:100%;max-height:100%;width:auto;height:auto;opacity:1;" id="hideAll"></img>
    <img id='gf' src="{% static 'images/img-loading.gif' %}" style="position:relative;margin-top:5%;margin-left:20% color:red;font-size:30px;width:auto;height:auto;left:25%;top:0"></img>
  </div>
  <div id='h1r' style='display:none;'>
    <h1  class="text-center" style="font-size:62px;font-family:'Bitter', serif;color:#3498DB;text-shadow: 1px 1px #F5B041;width: 100%;">Hello! Welcome to Shifty's Home Page</h1>
    <img style='width:100%;height:100%;margin-top:15px;margin-bottom:15px;'src='{% static 'images/data.png' %}' alt='That is really somehing!!' ><br>
    <p class="text-center" style='margin-top:10px;'><a style='margin-top:10px;margin-bottom:15px;border-color:#F5B041 ; background-color: #F5B041;font-size:20px;box-shadow: 2px 2px 5px 0 #999;'class="btn btn-primary btn-lg" href="{% url 'PF' %}" role="button"><span style="text-shadow: 1px 1px #999;">Learn More About Me</span></a></p>
 </div>
</div>
  <script>
    function init( ) {
      _oTag = document.getElementById("divLoading");
      gfi=document.getElementById("gf");
      wb=document.getElementById("hideAll");
      h1=document.getElementById("h1r");
      h1.style.display='block';
      _oTag.style.display = "none";
      gf.style.display='none';
      wb.style.display = 'none';
       //隱藏動畫
    }

    if (window.attachEvent) {
      window.attachEvent('onload', init);
    } else {
      window.addEventListener('load', init, false);
    }
  </script>
{% endblock %}

templates/first_app/login.html
<!DOCTYPE html>
{% extends 'first_app/profile.html' %}
{% load staticfiles %}
{% block body_block %}
<link href="https://fonts.googleapis.com/css?family=Bitter|Roboto+Slab" rel="stylesheet">
<link rel="stylesheet" href="{% static "css/login.css" %}"/>
<div class="container">
  <div class="jumbotron" style="text-shadow: 0px -1.6px 1px #2C3E50;color:#298089;font-family:'Roboto Slab', serif;background-color:white !important;border-style: solid;border-width: 0.5px 0.5px 0.5px 5px;border-color: #298089;padding-left:8%;margin-left:8%;margin-right:8%;margin-bottom:5%;">
    <h1 style='padding-bottom:40px;'>Please Login</h1>

      <form method="post" action="{% url 'first_app:user_login' %}" style='font-size:25px;'>
        {% csrf_token %}
        {# A more "HTML" way of creating the login form#}
        <label for="username" style='color:#F5B041;text-shadow: 0px -0.2px 0.3px #2C3E50;'>Username:&nbsp;&nbsp;</label>
        <input type="text" name="username" required><br><br><br>

        <label for="password" style='color:#F5B041;text-shadow: 0px -0.2px 0.3px #2C3E50;'>Password:&nbsp;&nbsp;&nbsp;</label>
        <input type="password" name="password" required>

        <input type="submit" name="" value="Login" id='sub' style='height:45px;margin-left:10px; width:100px; border-radius:5px;border-color:#F5B041 ; background-color: #F5B041;border-width:0;box-shadow: 2px 2px 5px 0 #999;color:white;text-shadow: 1px 1px #999;'>

      </form>

  </div>
</div>

{% endblock %}

templates/first_app/login0.html
{% extends 'basic_app/profile.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basic_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

templates/first_app/login1.html
{% extends 'basic_app/profile.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basic_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

templates/first_app/matplotlib.html
<!DOCTYPE html>
<link href="https://fonts.googleapis.com/css?family=Bitter|Roboto+Slab" rel="stylesheet">
{% extends 'first_app/profile.html' %}
{% load staticfiles %}
{% block body_block %}
<h2 style="font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.3px 0.3px #999;padding-bottom:15px;">Bubble Chart</h2>
<img src='{% static 'images/foo.png' %}' alt='supplier_relation' width="497.5" height="349.141201264489"><br>
<h2 style="font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.3px 0.3px #999;padding-bottom:15px;padding-top:15px">Double-Scale Chart</h2>
<img src='{% static 'images/rcode651.png' %}' alt='buyer_relation' width="497.5" height="600" style="position: relative;BOTTOM:15px;LEFT:0px"><br>
{% endblock %}

templates/first_app/other.html
<!DOCTYPE html>
{% extends 'first_app/profile.html' %}
{% load staticfiles %}
{% block body_block %}
<link href="https://fonts.googleapis.com/css?family=Bitter|Roboto+Slab" rel="stylesheet">
<h2 style="font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.3px 0.3px #999;padding-bottom:15px;">KNN-Cosine Application: User-Based Movies Recommender</h2>
<img src='{% static 'images/圖片3.png' %}' alt='supplier_relation' width="497.5" height="349.141201264489"><br>
<h2 style="font-family:'Roboto Slab', serif;color:#F5B041;text-shadow: 0.3px 0.3px #999;padding-bottom:15px;padding-top:15px;">KNN-Cosine Application: Item-Based Movies Recommender</h2>
<img src='{% static 'images/圖片4.png' %}' alt='buyer_relation' width="497.5" height="333" style="PADDING-BOTTOM:45px"><br>
{% endblock %}

templates/first_app/second.html
<!DOCTYPE html>
{% extends 'first_app/profile.html' %}
{% block body_block %}
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>First_APP</title>
    <link rel='stylesheet' href='{% static 'css/mystyle.css' %}'/>
  </head>
  <body>
    <h1>Hello, This is Shifty's Practice!!</h1>
    <h2>Hey!Django Fighter!!!This is what you want!</h2>
    <img src='{% static 'images/django.jpg' %}' alt='That is really somehing!!' ><br>
    {{insert_me}}:{{help_me}}
  </body>
</html>
{% endblock %}